[pytest]
pythonpath = .
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning:duckduckgo_search.*
    ignore:.*duckduckgo_search.*
    ignore:.*renamed to.*ddgs.*
    ignore:.*This package.*renamed.*
    ignore::starlette.testclient.StarletteDeprecationWarning
    ignore:Using `httpx` with `starlette.testclient`:DeprecationWarning
